---
:api_key: e15eb54df64edfe8b678dfa5f9f5258c
:password: 5fafbcadf8e4d6ce2a7b33c60ce5a501
:store: borntobeweird.myshopify.com
:theme_id: 55153667
:whitelist_files:
:ignore_files:
- config/settings.html
